import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash, randomUUID } from 'node:crypto';
import { Script } from 'node:vm';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

async function freePort() {
  const probe = createServer();
  await new Promise((resolve,reject)=>probe.listen(0,'127.0.0.1',resolve).once('error',reject));
  const {port}=probe.address();
  await new Promise(resolve=>probe.close(resolve));
  return port;
}

test('primeiro acesso, login, proteção de sessão e recibo original', { timeout: 20_000 }, async t => {
  const frontend=await readFile(path.join(root,'public','assets','app.js'),'utf8');
  assert.doesNotThrow(()=>new Script(frontend,{filename:'app.js'}),'frontend must parse as a classic browser script');
  const dir=await mkdtemp(path.join(tmpdir(),'gveg-auth-'));
  const port=await freePort();
  const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,HOST:'127.0.0.1',PORT:String(port),DB_PATH:path.join(dir,'test.sqlite')},stdio:'ignore'});
  const base=`http://127.0.0.1:${port}`;
  t.after(async()=>{child.kill(); await new Promise(resolve=>child.once('exit',resolve)); await rm(dir,{recursive:true,force:true});});
  let ready=false;
  for(let i=0;i<80;i++) { try { await fetch(`${base}/api/setup-status`); ready=true; break; } catch { await new Promise(resolve=>setTimeout(resolve,100)); } }
  assert.equal(ready,true,'server starts');

  const state=await fetch(`${base}/api/setup-status`).then(r=>r.json());
  assert.deepEqual(state,{needsSetup:true});
  const loginPage=await fetch(base);
  assert.equal(loginPage.status,200);
  assert.match(await loginPage.text(),/id="auth-form"/);
  const loginScript=await fetch(`${base}/assets/app.js`);
  assert.equal(loginScript.status,200,'the unauthenticated setup screen can load its JavaScript');
  assert.match(loginScript.headers.get('content-type'),/javascript/);
  assert.match(await loginScript.text(),/api\/setup-status/);
  assert.equal((await fetch(`${base}/assets/app.css`)).status,200,'the unauthenticated setup screen can load its styles');
  assert.equal((await fetch(`${base}/assets/supabase-test.bundle.js`)).status,401,'other application assets remain protected');
  const crossOrigin=await fetch(`${base}/api/setup`,{method:'POST',headers:{'content-type':'application/json',origin:'https://outside.example'},body:'{}'});
  assert.equal(crossOrigin.status,403);
  assert.equal((await fetch(`${base}/api/products`)).status,401);
  assert.equal((await fetch(`${base}/api/supabase-config`)).status,401,'Supabase client config requires the management session');
  assert.equal((await fetch(`${base}/supabase-test`)).status,404,'the Supabase test tool is not public');
  const setup=await fetch(`${base}/api/setup`,{method:'POST',headers:{'content-type':'application/json',origin:base},body:JSON.stringify({name:'Dona Teste',email:`owner-${randomUUID()}@example.test`,password:'senha-segura-123'})});
  assert.equal(setup.status,201);
  const setCookie=setup.headers.get('set-cookie');
  assert.match(setCookie,/HttpOnly/);
  const cookie=setCookie.split(';')[0];
  assert.equal((await fetch(`${base}/api/setup`,{method:'POST',headers:{'content-type':'application/json',origin:base},body:'{}'})).status,409);
  assert.equal((await fetch(`${base}/api/me`)).status,401);
  assert.equal((await fetch(`${base}/api/me`,{headers:{cookie}})).status,200);
  const supabaseConfigResponse=await fetch(`${base}/api/supabase-config`,{headers:{cookie}});
  assert.equal(supabaseConfigResponse.status,200);
  const supabaseConfig=await supabaseConfigResponse.json();
  assert.equal(typeof supabaseConfig.configured,'boolean');
  if(supabaseConfig.configured){assert.match(supabaseConfig.url,/^https:\/\//);assert.match(supabaseConfig.publishableKey,/^sb_publishable_/);}
  const supabasePage=await fetch(`${base}/supabase-test`,{headers:{cookie}});
  assert.equal(supabasePage.status,200);
  assert.match(supabasePage.headers.get('content-security-policy'),/connect-src 'self'/);
  assert.match(await supabasePage.text(),/Inserir e consultar/);
  assert.equal((await fetch(`${base}/assets/supabase-test.bundle.js`,{headers:{cookie}})).status,200);
  assert.equal((await fetch(`${base}/recibos/ferramenta`,{headers:{cookie}})).status,200);

  const post=async(path,body)=>fetch(`${base}${path}`,{method:'POST',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify(body)});
  const supplierResponse=await post('/api/suppliers',{name:'Fornecedor teste',email:'fornecedor@example.test'});
  assert.equal(supplierResponse.status,201);
  const supplier=(await supplierResponse.json()).item;
  assert.equal((await fetch(`${base}/api/suppliers/${supplier.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({name:supplier.name,document:supplier.document,email:supplier.email,phone:supplier.phone,notes:supplier.notes,active:false})})).status,200);
  assert.equal((await post('/api/purchases',{requestKey:randomUUID(),supplierId:supplier.id,purchaseDate:'2026-10-08',items:[{materialId:'missing',quantity:1,unitCost:1}]})).status,400,'inactive suppliers cannot be used for purchases');
  assert.equal((await fetch(`${base}/api/suppliers/${supplier.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({name:supplier.name,document:supplier.document,email:supplier.email,phone:supplier.phone,notes:supplier.notes,active:true})})).status,200);
  const productResponse=await post('/api/products',{name:'Bolsa teste',sku:`TEST-${randomUUID()}`,price:125.5});
  assert.equal(productResponse.status,201);
  const product=(await productResponse.json()).item;
  assert.equal(product.price_cents,12550);
  const priceUpdate=await fetch(`${base}/api/products/${product.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({name:product.name,sku:product.sku,price:130,active:true,priceReason:'Ajuste de teste'})});
  assert.equal(priceUpdate.status,200);
  assert.equal((await fetch(`${base}/api/products/${product.id}/price-history`,{headers:{cookie}}).then(r=>r.json())).items.length,2);
  const materialResponse=await post('/api/materials',{name:'Couro teste',code:`MAT-${randomUUID()}`,unit:'m²',quantity:4,minimumQuantity:1,unitCost:27.9,supplierId:supplier.id});
  assert.equal(materialResponse.status,201);
  const material=(await materialResponse.json()).item;
  assert.equal(material.quantity,4);
  assert.equal(material.unit_cost_cents,2790);
  assert.equal((await fetch(`${base}/api/materials/${material.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({name:material.name,code:material.code,unit:material.unit,minimumQuantity:2,supplierId:supplier.id,lastPurchaseDate:'',notes:'Atualizado',active:true})})).status,200);
  assert.equal((await fetch(`${base}/api/materials`,{headers:{cookie}}).then(r=>r.json())).items[0].quantity,4,'editing the material definition does not directly change on-hand stock');
  assert.equal((await post(`/api/materials/${material.id}/movements`,{kind:'loss',quantity:5,reason:'Teste de bloqueio de saldo negativo'})).status,409);
  assert.equal((await post(`/api/materials/${material.id}/movements`,{kind:'loss',quantity:1,reason:'Ajuste de teste'})).status,201);
  assert.equal((await fetch(`${base}/api/materials/${material.id}/movements`,{headers:{cookie}}).then(r=>r.json())).items.length,2);
  const bomResponse=await fetch(`${base}/api/products/${product.id}/materials`,{method:'PUT',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({materials:[{materialId:material.id,quantityPerUnit:1}]})});
  assert.equal(bomResponse.status,200);
  const productionResponse=await post('/api/production',{requestKey:randomUUID(),productId:product.id,plannedQuantity:1,startDate:'2026-10-08'});
  assert.equal(productionResponse.status,201);
  const order=(await productionResponse.json()).item;
  const completeOrder=()=>fetch(`${base}/api/production/${order.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({status:'completed',producedQuantity:1,approvedQuantity:1,defectiveQuantity:0,laborCost:19,additionalCost:0,consumptions:[{materialId:material.id,quantity:1}]})});
  const completion=await completeOrder();assert.equal(completion.status,200);assert.equal((await completion.json()).item.unit_cost_cents,4690);
  assert.equal((await completeOrder()).status,200,'completing a production order twice does not consume material twice');
  assert.equal((await fetch(`${base}/api/products`,{headers:{cookie}}).then(r=>r.json())).items[0].stock_quantity,1);
  const purchaseRequest={requestKey:randomUUID(),supplierId:supplier.id,purchaseDate:'2026-10-08',items:[{materialId:material.id,quantity:1,unitCost:31}],freight:5,discount:0,initialPaid:0};
  const purchaseResponse=await post('/api/purchases',purchaseRequest);assert.equal(purchaseResponse.status,201);const purchase=(await purchaseResponse.json()).item;assert.equal(purchase.total_cents,3600);
  assert.equal((await post('/api/purchases',purchaseRequest)).status,200,'retry does not duplicate purchase stock entry');
  const cancelPurchase=await post(`/api/purchases/${purchase.id}/cancel`,{reason:'Compra de teste cancelada'});assert.equal(cancelPurchase.status,200);
  const restoredMaterial=(await fetch(`${base}/api/materials`,{headers:{cookie}}).then(r=>r.json())).items[0];
  assert.equal(restoredMaterial.quantity,2);
  assert.equal(restoredMaterial.unit_cost_cents,2790,'cancelling a purchase restores the previous material cost');
  const purchase2=(await post('/api/purchases',{requestKey:randomUUID(),supplierId:supplier.id,purchaseDate:'2026-10-08',items:[{materialId:material.id,quantity:0.1,unitCost:31}]}).then(r=>r.json())).item;
  const purchasePayment={requestKey:randomUUID(),amount:1,paidAt:'2026-10-08',method:'PIX'};
  const payPurchase=()=>fetch(`${base}/api/purchases/${purchase2.id}/payments`,{method:'POST',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify(purchasePayment)});
  assert.equal((await payPurchase()).status,201);
  assert.equal((await payPurchase()).status,200,'purchase payment retries do not duplicate cash movements');
  assert.equal((await post(`/api/purchases/${purchase2.id}/payments`,{requestKey:randomUUID(),amount:2.1,paidAt:'2026-10-08',method:'PIX'})).status,201);
  const managerEmail=`manager-${randomUUID()}@example.test`;
  const managerResponse=await post('/api/users',{name:'Gerente teste',email:managerEmail,password:'senha-gerente-123',role:'manager'});
  assert.equal(managerResponse.status,201);
  const managerLogin=await post('/api/login',{email:managerEmail,password:'senha-gerente-123'});
  assert.equal(managerLogin.status,200);
  const managerCookie=managerLogin.headers.get('set-cookie').split(';')[0];
  assert.equal((await fetch(`${base}/api/users`,{headers:{cookie:managerCookie}})).status,403);
  assert.equal((await fetch(`${base}/api/audit`,{headers:{cookie:managerCookie}})).status,403);
  assert.equal((await fetch(`${base}/api/products`,{headers:{cookie:managerCookie}})).status,200);
  const permissionUpdate=await fetch(`${base}/api/role-permissions`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({modules:{materials:false}})});
  assert.equal(permissionUpdate.status,200);
  assert.equal((await fetch(`${base}/api/materials`,{headers:{cookie:managerCookie}})).status,403);
  assert.equal((await fetch(`${base}/api/products`,{headers:{cookie:managerCookie}})).status,200);
  assert.equal((await fetch(`${base}/api/role-permissions`,{method:'PATCH',headers:{cookie:managerCookie,'content-type':'application/json',origin:base},body:JSON.stringify({modules:{materials:true}})})).status,403);
  assert.equal((await fetch(`${base}/api/role-permissions`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({modules:{materials:true}})})).status,200);

  const customerResponse=await post('/api/customers',{name:'Cliente teste',document:`DOC-${randomUUID()}`,email:'cliente@example.test'});
  assert.equal(customerResponse.status,201);
  const customer=(await customerResponse.json()).item;
  assert.equal((await fetch(`${base}/api/customers/${customer.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({...customer,active:true,phone:'11999999999'})})).status,200);
  const requestKey=randomUUID();
  const saleResponse=await post('/api/sales',{requestKey,customerId:customer.id,saleDate:'2025-06-15',dueDate:'',historical:true,initialReceived:30,items:[{productId:product.id,quantity:1,unitPrice:125.5}]});
  assert.equal(saleResponse.status,201);
  const sale=(await saleResponse.json()).item;
  assert.equal(sale.received_cents,3000);
  assert.equal((await fetch(`${base}/api/products`,{headers:{cookie}}).then(r=>r.json())).items[0].stock_quantity,1,'historical sale does not reduce finished stock');
  const margin=await fetch(`${base}/api/dashboard?from=2025-06-01&to=2025-06-30`,{headers:{cookie}}).then(r=>r.json());
  assert.equal(margin.gross_profit_estimate_cents,7860);
  assert.equal(margin.gross_profit_coverage,1);
  assert.equal((await post('/api/sales',{requestKey,customerId:customer.id,saleDate:'2025-06-15',historical:true,items:[{productId:product.id,quantity:1,unitPrice:125.5}]})).status,200,'retry does not create a duplicate sale');
  const salePayment={requestKey:randomUUID(),amount:20,paidAt:'2026-10-08',method:'PIX'};
  const salePaymentRequest=()=>fetch(`${base}/api/sales/${sale.id}/payments`,{method:'POST',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify(salePayment)});
  assert.equal((await salePaymentRequest()).status,201);
  assert.equal((await salePaymentRequest()).status,200,'a repeated payment request is idempotent');
  assert.equal((await fetch(`${base}/api/sales/${sale.id}/payments`,{method:'POST',headers:{cookie,'content-type':'application/json',origin:base},body:JSON.stringify({requestKey:randomUUID(),amount:100,paidAt:'2026-10-08',method:'PIX'})})).status,409);
  const cash=await fetch(`${base}/api/dashboard?from=2026-10-01&to=2026-10-31`,{headers:{cookie}}).then(r=>r.json());
  assert.equal(cash.received_cents,2000,'historical receipts are excluded from cash flow');
  const receiptWithSale=await fetch(`${base}/recibos/ferramenta?sale=${sale.id}`,{headers:{cookie}}).then(r=>r.text());
  assert.match(receiptWithSale,/Cliente teste/);
  assert.match(receiptWithSale,/DOMCONTENTLOADED/i);

  const expenseResponse=await post('/api/expenses',{description:'Aluguel teste',category:'Aluguel',amount:100,expenseDate:'2026-10-01',dueDate:'2026-10-10'});
  assert.equal(expenseResponse.status,201);
  const expense=(await expenseResponse.json()).item;
  const payExpense=(amount,requestKey=randomUUID())=>post(`/api/expenses/${expense.id}/payments`,{requestKey,amount,paidAt:'2026-10-08',method:'PIX'});
  const expensePaymentKey=randomUUID();assert.equal((await payExpense(25,expensePaymentKey)).status,201);
  assert.equal((await payExpense(25,expensePaymentKey)).status,200,'a repeated expense payment is idempotent');
  assert.equal((await payExpense(80)).status,409);
  assert.equal((await payExpense(75)).status,201);

  const source=await readFile(path.join(root,'Recibo_pdf','recibo_auto.html'));
  const served=await fetch(`${base}/recibos/ferramenta`,{headers:{cookie}}).then(r=>r.arrayBuffer());
  assert.equal(createHash('sha256').update(source).digest('hex'),createHash('sha256').update(Buffer.from(served)).digest('hex'));
  const logout=await fetch(`${base}/api/logout`,{method:'POST',headers:{cookie,'content-type':'application/json',origin:base},body:'{}'});
  assert.equal(logout.status,200);
  assert.equal((await fetch(`${base}/api/me`,{headers:{cookie}})).status,401);
});
